SELECT 
	CAST(DS_BATCH_DELIVERY.DELIVERED_TIME AS DATE) AS SDATE,
	DS_GROUP_TYPE.NAME AS GT, 
	DS_GROUP.DISPLAY_NAME AS NAME, 
	DS_GROUP.DESCRIPTION AS DIS,
	ROUND (SUM(DS_BATCH_DELIVERY.DELIVERED_WEIGHT),0) as DW,
	ROUND (SUM(DS_BATCH_DELIVERY.DELIVERED_WEIGHT * DS_BATCH_DELIVERY.ACTUALDM_PERC/100),0) AS DWS,
	ROUND (SUM(DS_BATCH_DELIVERY.WEIGHBACK_AMOUNT), 0) as DWWB
	FROM DS_BATCH
	INNER JOIN DS_BATCH_DELIVERY ON	DS_BATCH_DELIVERY.BATCH_ID = DS_BATCH.ID 
	INNER JOIN DS_GROUP ON	DS_GROUP.ID = DS_BATCH_DELIVERY.GROUP_ID
	INNER JOIN DS_GROUP_TYPE ON DS_GROUP_TYPE.ID = DS_GROUP.GROUP_TYPE
	WHERE DS_BATCH_DELIVERY.DELIVERED_TIME >= CURRENT_DATE - 100 
	GROUP BY SDATE,GT, NAME, DIS